### ISSUE TITLE
Authentication using Jira API tokens

### ISSUE THREAD

**Issue by Marcus-James-Adams** [datreeio/jira-backup-py#1]
It would be useful from a security point of view if it was possible to use the JIRA cloud user API tokens instead of a password to save the password being listed or if mandatory 2fa on passwords is enabled

**Comment by eyarz** [comment]
I update the script to work w/ [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html), instead of personal authentication because your right and this is the best practice in this case.
