### ISSUE TITLE
Module boto is deprecated

### ISSUE THREAD

**Issue by MATMAF** [datreeio/jira-backup-py#17]
The module boto is deprecated since 2020 and the last supported Python version is 3.4.

So when I try to use the script with Python version 3.12.6, I get this error:
<img width="818" alt="image" src="https://github.com/user-attachments/assets/373d51e3-f87d-48aa-b830-3fad98906da5">

To fix this error you can try to use [boto3](https://github.com/boto/boto3).
This is the current AWS SDK for Python.

**Comment by eyarz** [comment]
did you test it with boto3?
if it's working as expected, open a PR and I will merge it

**Comment by MATMAF** [comment]
I created the pull request: #18

**Comment by MATMAF** [comment]
Now with the correct requirements.txt file #19
