### ISSUE TITLE
Update to Python3.

### ISSUE THREAD

**Issue by jeremy-j-ackso** [datreeio/jira-backup-py#6]
Python2 end of life is coming up, should update this to use Python3.

https://pythonclock.org/

**Comment by eyarz** [comment]
Looks like the code is already python3 compatible:
![Screen Shot 2019-05-26 at 11 44 11](https://user-images.githubusercontent.com/19731161/58379435-e636d880-7fab-11e9-94a0-0ffd7c95a204.png)
I will update the readme file
